//
//  Profile.swift
//  Atomic Habits
//
//  Created by Apeel Subedi on 20/01/2025.
//

/*
This file defines the `Profile` model, which represents an individual user profile.

- Major Components:
  - `id`: A unique identifier for each profile (generated by default using UUID).
  - `name`: The display name of the profile (e.g., "John Doe").

- **How It Interconnects**:
  - This model is used to manage and represent profile data within the app.
  - It is referenced by other pages, such as `ProfileListView`, where profiles are displayed, or modified.
  - Transition-related code: This struct is consumed wherever user profiles are handled, including `IntroView` when transitioning to `ProfileListView`.
*/



import Foundation

/// A simple model for each profile.
struct Profile: Identifiable, Codable {
    let id: String       // Unique ID (e.g. UUID)
    var name: String     // Display name, e.g. "John Doe"
    
    init(id: String = UUID().uuidString, name: String) {
        self.id = id
        self.name = name
    }
}
